### PR TITLE
fix: skip button now skips onboarding instead of returning to first page

### LINKED ISSUE #17: onboarding cards: skip button doesn't skip, but returns to the first onboarding page

### PR DESCRIPTION
**Pull request by Sednaoui**
Fixes #17

### CODE REVIEW

File: lib/features/onboarding/onboarding_screen.dart [hunk 1]
```diff
@@ -131,10 +131,10 @@ class _OnboardingScreenState extends State<OnboardingScreen> {
             TextButton(
               onPressed: () {
```
Comment (andrewwahid) [inline lib/features/onboarding/onboarding_screen.dart]: `onPressed: () => _completeOnboarding(),`
this removes the delay and the animation to the latest page which yields a more expected behavior for the skip button

**Review by andrewwahid — CHANGES_REQUESTED** [review]
should we also have the skip button show from the first onboarding page (current behavior is that skip button shows starting from the second page)
